In [2]:
import pandas as pd
import numpy as np
import os
os.environ['MKL_NUM_THREADS'] = '1'
from collections import Counter
import itertools
import json
import scipy.sparse as sparse
import pickle
import torch
import misc.util as util
from torch import nn

import importlib
from torch.utils.data import DataLoader
from misc.loader import AEDataset
from misc.util import *
from tqdm.auto import tqdm
from eval.rec_eval import *
import neuralsort.pl as pl
from models.loss import neuPrecLoss
from misc.loader import RecDataset
import models
from models.loss import *

In [34]:
import pickle
with open("data/parsed/ml-1m-l-1-100", 'rb') as f:
    tr, val = pickle.load(f)

In [37]:
tr

<6034x2811 sparse matrix of type '<class 'numpy.float64'>'
	with 566160 stored elements in Compressed Sparse Row format>

In [38]:
n_users, n_items = tr.shape
ae_dataset = AEDataset(tr)
total_anneal_steps = 50000
anneal_cap = 0.2


In [40]:
from lightfm import LightFM
model = LightFM(no_components=32,
                learning_rate=1e-2,
                item_alpha=0.01,
                user_alpha=0.01,
                max_sampled=100,
                loss='bpr')
model.fit_partial(tr, epochs=10,)

In [30]:
ub, uv = model.get_user_representations()
ib, iv = model.get_item_representations()

In [31]:
w = util.get_wrapper(uv, iv, ub, ib)

In [33]:
leave_k_eval(w, tr, val, leavek=1, K=5)

{'precision': 0.3824991713622804,
 'map': 0.23115677825654685,
 'ndcg': 0.26854139867777893}

In [6]:
vin_dense = torch.FloatTensor(np.asarray(vin.todense())).cuda()
tin_dense = torch.FloatTensor(np.asarray(tin.todense())).cuda()

NameError: name 'vin' is not defined

In [7]:
list(zip([1,2],[3,4]))

[(1, 3), (2, 4)]

In [16]:
import models.ae
importlib.reload(models.ae)
model = models.ae.MultiDAE([200] + [n_items], n_users=n_users, dropout=0.5)
x = model.rank_items(3, tr, np.asarray([1,2,3]))
print(x)

[(2, 0.0126362275), (1, 0.0011439759), (3, -0.02918803)]


In [17]:
loader = DataLoader(ae_dataset, batch_size=256, shuffle=True, num_workers=4)

In [21]:
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

for epoch in (range(1, 5 + 1)):
    model = model.train()
    model.training = True
    tr_losses = []
    for uid, row in  (loader):
        loss = None 
        scores = model.forward(row, uid)
        if total_anneal_steps > 0:
            anneal_cap = min(0.1, 1. * 1 / total_anneal_steps)
        else:
            anneal_cap = 0.1
            
        loss  = models.loss.MSELoss(row, scores)
        model.zero_grad()
        (loss.mean()).backward()
        tr_losses.append(loss.detach().unsqueeze(-1)) 
        optimizer.step()
        print(loss)

tensor([117.4600, 286.4197,  65.7153,  81.8573,  39.5820,  42.5460,  14.6702,
        193.3005, 115.5951,  56.5382,  32.7032,  20.6026,  26.6044,  72.4638,
        366.6427, 287.7138,  29.5673, 497.4019,  21.7500,  96.6405,   6.6405,
        378.5478,  50.8278, 126.4862,  11.6234,  15.5325,  55.6529,  44.5503,
         33.6551, 114.6755,   8.6863,  16.6626,  22.5990, 105.2805, 172.6479,
         66.4041,  11.8986, 197.7281, 327.1071, 162.4853,  33.6933,  35.5338,
         20.7255, 172.5473,  34.6877,  58.8168,  97.9286,  17.1144,   8.1929,
         17.9060,  23.3008, 102.7108,  24.3877,  70.3678, 139.4349,   9.8268,
          6.1404,  29.5653,  54.3115, 188.3158,  13.8044,  28.5909,  25.0124,
         63.5011, 116.6791,  31.6912, 120.1187,  35.6465, 116.1934,  26.3773,
        442.5891,   7.2229,  81.6441,  58.5589,  49.7743, 272.7033, 106.6702,
         24.9417,  69.3891,  20.6295,  45.0643, 190.0102,  33.4722, 123.5978,
         27.8585,  35.3823,  13.4848,  24.5704,  38.2576,  94.49

tensor([ 59.9669,   9.2119, 396.1201, 136.6355,  55.4005,  62.2689,  37.6697,
        163.3080, 148.0048,  96.4116,  17.5775,  12.4617, 108.5077,  29.8978,
         41.8876, 170.3676,  34.6926,  14.7908,  95.9990,  92.4984,  23.7586,
        131.9558,  55.7615, 228.3190,  25.0191,  94.1251,  52.1510,  37.8341,
        237.6209,  45.0546,  18.5220, 177.7865, 140.3499, 122.1933,  45.1052,
         26.9741, 269.9996,  52.1672,  57.3574,  27.5533,  12.3990, 455.3328,
         39.2794,  22.1645,  42.2670,  48.4667, 161.8363,  25.1137,  29.7090,
         90.1683,  84.5994,  93.8575, 215.0044,  26.0234,  59.0993, 105.9388,
         21.3633,  21.5158, 151.1798,   7.5457,  35.8264,  41.4577, 131.4371,
        190.9295, 328.8539,  25.2513, 119.0039,  19.1278,  30.9047,  15.4061,
         38.0704,  95.0489, 220.1408,  23.0970,  55.5821,  39.0854, 318.0393,
         58.3189,  79.1648, 258.3784,  26.3643,  77.7344,  11.5396,  89.2016,
        185.4530,  51.7324, 101.9952,  64.4463,  77.4932, 114.81

tensor([ 27.3579, 210.9326,  51.8282,  44.8182,  24.6313,  14.5846,  43.0086,
        282.7767,  27.3265,  62.8494,  99.3385,  58.4021, 349.8619,  74.9614,
        101.5344, 309.8560,  64.7061,  46.6944,  38.9500, 195.4605, 228.6394,
         93.4997,  28.8875,  58.5711,  18.8713, 179.3668,  46.4215,  18.2881,
         28.7264,  15.8748,  23.0656, 113.3946,  28.4794, 112.5756,  23.5821,
        580.9188,  32.5946,  32.8106, 171.4842,  39.0452,  86.0601, 109.6088,
         36.0541, 177.7217,  43.2614, 116.8956,  34.9414,  99.9091, 265.3013,
        238.1642,  29.9430,  65.9202,  42.4110, 149.8705,  93.8546,  76.2430,
         34.2264,  69.9763,  27.1393,  24.1837, 111.3315,  24.1141,  33.5202,
        169.2002,  75.0522,  45.3195, 123.3743,  79.0591,  24.6380,  32.3486,
         16.7652, 106.3115,  31.1444,  89.7113,  73.2832, 206.7518,  85.6375,
         33.9735,  68.8983, 106.1284, 215.0960,  31.4347,  16.3344, 182.9655,
         36.4293,  31.0848, 177.5234, 145.8458,  28.5041, 600.18

tensor([ 77.4570,  83.0449,  46.2016,   8.8314,  26.8250,  42.5064, 173.6888,
         68.5943,  24.3186,  41.2402,  27.8670,  44.9586,  16.8868,  22.1048,
         13.4295, 151.3004,  23.7206, 112.7631, 300.9360,  36.9696, 108.8356,
         23.1857,  35.7146,  36.4524,  27.2478,   9.7352, 284.4702,  18.7018,
         51.4761,  49.5990,  41.3453, 135.0311,  75.8121, 103.7297,  21.9392,
         18.6782, 166.8221, 106.2686,  43.6649, 241.3504, 115.8188, 183.5425,
         18.9900,  46.8522, 245.8566,  30.1701,  45.7556, 131.1743, 312.5179,
         24.8713,  22.5070, 137.4194, 233.0807,  20.5516,  91.8336,  35.2946,
        161.4788,  14.5633,  37.2938,  27.0872,  69.1223,  22.3171, 118.9724,
         83.4392,  24.2213, 113.4885,  54.5268,  18.9996,  33.4200,  65.8647,
         14.7209,  45.5539,  81.5469, 108.6241, 158.4895,  15.7887,  62.0998,
         12.0018,  20.6418,  47.8108,  22.8398,  26.9850,  58.7007, 128.8454,
         17.7980,  34.7259,   8.4123, 154.2922,  19.6840,  12.31

tensor([ 31.7081,  18.6831,  78.8398,  10.6590,  46.3483,  18.3341,  19.8141,
         88.4615,  40.4108, 101.8274,  13.2084,  22.2253,  14.1689,  24.3449,
         74.3339,  12.4206,  25.2249,  32.2098,  39.6486,  46.3315,  31.0006,
         35.3125, 121.0542,  49.7255,  71.6052, 101.4831,  81.9860,  75.1212,
         33.6295,  28.7951,  63.7510, 110.0280,  29.4556,  91.0118,  55.6286,
        143.9498,  73.4168,  79.7388,  55.5174,  10.8446,  43.4517,  76.6804,
         85.3461, 250.6389, 144.8897,  50.3449, 173.1325,  13.5330, 114.5647,
         13.4807, 208.7364,  53.9773, 218.5154,  19.1821,  20.8029,  24.6444,
        138.0505,  65.7161, 191.3309,  43.3450,  83.0709,  64.6204,  16.3602,
        113.0676,  21.0281, 142.5901,  13.9551,  34.2753, 170.4828,  80.2406,
        134.8135,  23.8019, 129.4702,  45.9262, 267.6263,  16.0074,  39.7853,
         18.5971,  17.9919, 259.1789, 349.7615,  56.7514,  28.1970,  22.3561,
        181.3813,  44.5015,  14.0744,  51.0220,  85.0257,  19.10

tensor([144.4494, 130.6663, 251.4738,  12.8563, 173.3746,  65.5280,  24.8896,
         23.6423,  29.1909,  45.0769, 167.4054, 444.7451,  12.0980, 291.1043,
         10.2417,  77.0436,  19.1032, 376.0352,  54.9631,  22.7429, 293.8555,
         94.7775,  52.9225,  17.8845,  82.9985,  18.9948, 110.4523,  11.8798,
         48.8191,  43.8807,  64.8387,  32.9872, 143.9867,  44.9720,  37.3498,
         18.9747,  18.2597, 100.2443,  39.0048,  20.6422,  30.2092,  52.7891,
         54.9126,  15.2650,  16.1570, 176.7253,  63.5741, 113.3232,  21.2585,
         51.2719,  18.8773,  63.1055,  20.9632,  62.2206,  19.7121,  18.2658,
         18.1714,  61.1495,  25.6631,  52.4902,  57.0225,  35.8342,  38.4670,
         24.8610,  53.8614,  38.3053,  38.2552, 181.0058,  40.4376, 102.0316,
        165.1156,  42.8410,  26.4284,  58.6596,  39.1892,  41.1744,   8.7913,
         31.5210,  16.8048, 216.2101, 230.0790,  72.2067, 106.1569, 126.2401,
         12.4618,  49.9700,  70.2531,  20.4907,  22.6764,  34.24

tensor([ 43.4358, 384.9022,  28.5035,  48.4594,  43.9199,  45.8696,  63.6230,
         19.7363,  61.3160, 147.2905,  55.9453,  49.8148, 104.9368,  85.5538,
        204.8384,  35.7513,  50.1998,  48.4805,  36.5871, 149.0882, 101.2753,
         22.1061,  70.5847, 119.3566,  32.9459,  66.4417,  20.7363, 100.9854,
         22.9250,  83.3833,  11.6727,  58.4341, 282.1960, 151.6936,  35.2112,
         40.4890, 145.0205,  70.4145,  28.8464, 104.6561,  95.7069, 887.3410,
         13.0120,  34.3866, 115.0602,  18.1894,  18.5344,  22.6987,  80.3573,
         33.1103,  56.7767, 165.4996,  67.1457,   6.4240,  60.3152,  35.0818,
        159.8725,  43.6949,  28.0913, 167.4247, 146.5230, 261.5248, 117.2722,
         21.8503, 108.7507, 110.6321,  30.2714, 115.5787, 143.2671,  61.8531,
        115.5652,  88.2750,  33.9830,  73.2290,  70.7224,  16.1172,  50.5058,
         71.6295, 242.6221,  77.4007, 133.0944,  46.3289, 313.7905,  11.7540,
        189.5886,  39.6639,  70.9738,  49.0029,  63.8701,  40.64

tensor([ 26.5117,  47.1059,  85.7011, 135.9971,  51.2481,  15.2370,  21.6599,
         19.6969,  19.1683, 204.1190,   7.1839,  12.5531,  61.1133,  14.3192,
         80.1883,  59.6027, 131.1741,  26.4604,  70.8949, 108.0348,  10.1463,
         31.5284,  27.1030,  93.4904, 109.5106,  30.2012, 204.4989,  33.3053,
         29.7444,  33.3235,  50.8944,  51.5791,  29.0208,  54.7809,  90.3141,
         50.6569, 117.5799,  25.0501,  12.0217,  15.0065,  44.0754,  45.6076,
         28.1875, 139.2065,  37.7884, 198.8974,  56.3110,  18.0588, 147.6985,
         48.3232, 110.0325,  55.6102,  95.3181,  36.0819,  61.6187,  19.5006,
         10.7819, 105.7009,  28.6292,  41.8657,   7.4660, 341.5931,  32.6833,
         88.6590, 142.0941,  11.6046,   6.3748,  32.0695,  22.0107,  39.9825,
         30.3780, 122.1998,  66.0462,  37.4306, 108.3778,  19.1799,  44.8137,
         62.1034,  64.4963,  28.7534,  28.7806, 113.3573, 138.2471, 112.5216,
        199.9839,  36.5994,  62.9154,  13.9752,  57.7243,  91.33

tensor([ 44.7964, 134.1852, 352.2509, 343.8592, 198.1577,  35.6756,  13.4591,
         10.9900,  32.9210,  67.2206,  20.7051,  86.2546,  25.5147,  28.7438,
         20.8425,  12.2162,  31.6112,  13.3957,  45.5393,  25.0193,  13.9961,
         16.6408,  52.4863, 222.1318,  54.3066, 235.9819,  12.6982, 137.2860,
         29.3185,  17.8412,  13.0031,  56.8305,  95.0704, 346.0730,  51.7700,
        156.3448,  43.6654,  60.2202,  25.5039,  26.5025,  68.6376,  25.0961,
         31.2860,  58.6584,  39.5193,  65.3254,  73.1698,  62.3669,  18.8559,
         22.0119,  92.6931,  57.3910,  55.3675,  15.0925,  94.2619,  14.9825,
        154.9714,  74.1616,  12.6584, 182.0204,  93.3560,  24.4365,  15.2080,
         55.9872,   6.8788,  41.8168,  10.9381,  29.9916,  20.7694,  22.5787,
         88.0581,  13.9216,  20.0447, 558.8986, 190.1851, 145.2938,  22.5829,
         17.9296,  33.6257, 244.0197,  43.5481,  16.6556,  75.8504,  64.5972,
        124.9448,  13.6159,  51.8939, 108.7069,  62.9512,  88.25

tensor([ 27.3087,  34.1701, 142.8525,  12.6343,  85.6913,  25.4858, 128.7737,
         69.2241,  53.0617, 172.5581,  15.1585,  48.9202,  58.0923,  65.1547,
         11.4230,  31.2342, 210.2646,  96.7201,  17.5985,  31.6043, 130.1523,
         55.9756,  72.7468,  35.2990,  84.2980,  46.2864,  79.1142,  73.3038,
         84.1284,  17.4318,  48.6759,  15.1418, 110.7382, 117.3887,  19.1416,
        103.2393, 275.4919,  42.4102,  26.8045,  20.4857,  66.5068,  50.8469,
         42.7610,  15.2152, 116.7485, 289.1054,  60.2332,  67.0038,  29.7923,
         22.8198,  19.7096, 145.0250,  23.5079, 102.0034,  27.4688,  38.4033,
         21.1583,  21.7855,  37.3152,  68.3706,  20.5049,  81.2824,   5.8650,
         14.9745,  35.8995, 264.0221,  27.3507,  55.3744,  75.8129,  39.2708,
         16.2708, 155.5831,  37.1500,  21.3547,  27.0772,  44.5000, 115.2533,
         42.1756,  68.0077, 101.4300, 156.6080,  75.8666, 120.2739,  20.6559,
        127.8650,  35.5721,  49.8308,  12.2546,  22.2357,  80.70

tensor([ 19.4654,  12.8854,  11.6719,  59.8533, 179.0400,  64.2015,  71.8291,
         94.1751,  42.3032,  17.4621,  49.9487,  97.0484,  95.5970,  22.2582,
         16.6146,  27.9089,  50.5312,  41.1455,  16.5285,  37.4899, 169.8977,
         36.9712,  85.2454,  59.2957,  35.1332, 114.6419,  39.5861,  40.0589,
         85.2712,  70.9497, 128.2411,  70.1890,  15.3660,  30.3411,  60.0765,
        104.9457,  18.9223, 351.8327,  75.7354, 133.6851,  19.3001,  75.6075,
         57.0594,  38.9386,  61.7862,  94.4089,  46.8245,  67.2267,  30.0963,
         23.4043,  72.1122,  11.0835,  46.4439,  34.6180,  71.5200,   9.1459,
         22.3976,  74.6396,  67.3788,  44.1544,  95.5366,  76.2711,  23.4279,
         22.7259,  19.5635, 147.0666,  71.2219,  47.4456, 156.3670,  56.2629,
         24.2759,  15.6279,  20.7707, 125.1254,  19.0001,  14.1313,  71.1961,
        113.2962,  87.3295,  21.2742,  18.5337,  25.9714,  27.4864,  49.4763,
         14.8392,  30.8142,  29.6550,  31.1425,  35.8861,  28.60

tensor([ 44.1916,  26.9465,  41.0776,  80.8043,  10.8887,  60.3340, 179.4145,
         13.6215,  83.0645,  44.3161,  41.3821,  84.2748,  41.3616,  45.0251,
         18.1079, 376.1572,  21.0288,   8.1986,  25.0391,  12.8205,  82.6458,
        137.7116,  13.0116,  35.0087,  76.7148,  79.9192,  19.6447,  64.5566,
        136.3967,  58.2056,  76.8641,  84.6034, 157.1671,  18.0364,  12.2669,
        273.2532,  79.9311,  19.3793,  51.7532,  42.0603, 126.5151,  83.4157,
         80.2840, 206.8626,  27.9662,  50.2678, 274.5388,  21.1132,  50.4589,
        223.0692,  18.2088,  19.9622,  69.0278,  52.2903,  90.6217, 103.3317,
         17.8923,  79.1171,  32.1104, 169.9863,  31.7317,  76.1624,  34.8905,
         19.0533,   7.8099,  17.9604,  48.9382,  21.2281,  12.8639,  71.1075,
         19.4279,  24.6922,  19.6584,  66.5645,  15.8251,  43.2453,  55.2252,
          8.3131, 112.1126,  15.2739,  18.2622, 181.4382, 135.0235,  77.7271,
        147.5692,  18.2244,  35.1120,  17.6882, 249.0107,  88.45

tensor([ 57.9181,   9.5317,  64.5961,  61.1812,  58.7412, 160.9528,  13.8042,
         36.0315, 141.9069, 106.9580,  25.4959,  14.8863,  66.4183,  65.1614,
         26.1140,  40.8248,  34.0337,  78.0216,  28.6209,  94.1944,  57.3540,
         97.6658,  80.0590,  42.2976,  17.6748, 168.7331,  60.0985,  95.1636,
        117.6328, 280.9542,  96.2874,  41.6468,  16.4867, 144.3847, 116.7779,
        280.1573, 138.4702,  25.8765,  26.9228,  14.2019,  17.9975, 130.2004,
         21.2219,  14.9426,  67.9634,  47.1563,  60.7969,  12.1575,  18.6443,
         97.5166,  10.8871, 177.1098,  27.9650,  44.5225,  31.8843, 235.4531,
        142.8025,  93.6208, 100.6257,  18.5227, 224.8346,  14.2344,  35.3903,
         26.9988,  37.5246,  61.1897,  23.1100,  13.0678,  14.0376,  61.2211,
         21.9768,  25.8639,  20.3667, 222.8074,  20.0074,  45.3461,  90.3795,
        195.4612,  61.5955,  12.6249,  51.5781,  28.1512,  11.2206,  46.4799,
          7.1008,  25.2964,  62.7902,  18.3155,  68.3921,  17.43

tensor([ 60.9496,  15.7520,  24.5479,  37.1894,  22.5458,  97.8840,  40.3605,
         34.6762,  12.2438,  91.9718, 404.1007, 381.3037,  62.5713,  12.1682,
         45.9873, 147.1126,  93.5268,  11.4784,  95.4066,  11.1548, 166.3330,
         55.7282, 108.2311,  40.8114, 314.6887,  33.2072,  74.5099, 153.0566,
         71.2384, 101.9022,  19.0448,  23.7621,  16.8449,  19.8732,  63.0215,
         50.4204,  52.9533, 157.1218, 103.3417, 269.6053,  45.6667, 177.1373,
        122.9908, 354.1327,   9.8954,  27.5252, 106.8409, 142.0616,  26.9153,
         31.2387, 153.1994,  57.6373,  23.0323,  77.9146,  78.8924,  16.8632,
        235.9133, 174.2650,  20.8460, 122.8376,  62.6287, 168.1778,  70.5496,
         61.9021,  27.2907,  18.6553,  29.3120,  15.9456,  87.1000, 162.7762,
        159.4936,  61.1986,  36.4851,  21.0826,  28.3714, 123.1200,  87.0350,
         66.1447,  89.8831,  17.5845,  41.7269,  12.9574,  24.0255, 113.5458,
         66.1920,  25.9956,  16.5034,  67.3869,  35.5655,  43.25

tensor([ 35.0346,  44.2136,  89.1773,  37.0657,  19.7278, 171.8012, 166.6797,
         96.5028,  65.0389, 154.6359,  95.9081,  95.5208,  44.7664,  25.9098,
         26.0746,  55.3367,   9.3074,  19.3423, 107.4019,  61.9833,  29.4876,
         50.8796, 193.0440,  19.7120, 182.6303, 133.9791,  16.2413,  81.0445,
         22.3435,  44.5171,  18.2033,  43.6651, 319.4399, 119.1547,   7.1493,
        119.6569,  16.2997,  87.9193,  16.0175, 113.6045,  24.2677,  61.7500,
         60.1073, 133.9605, 210.2530,  85.1385, 113.0407,  23.2628,  42.5020,
         84.2152,  27.0181,  85.4175,  45.4419,  99.3489,  16.8392,  29.0566,
         69.7146,  15.5667,  68.9116,  14.7523,  22.7869, 114.1980,  18.6611,
        118.2826,  27.3042,  33.5465,  14.4121,  21.9582,  68.7702,  17.0555,
        128.9631,  68.1620, 101.3820,  70.2614, 172.2339,  28.2867,  16.0828,
         79.0330,  92.3885,  19.2897, 304.5098, 130.3894,  63.9582,  21.7394,
        263.4635,  30.3321,  39.2228,   9.3876,  14.4902,  17.45

tensor([ 84.6701,  66.0440,  61.7854,  90.3084, 207.6042, 105.3241, 291.0384,
        289.3966,  90.1331,  45.3687,  31.6447,  17.3757, 305.1582,  61.8038,
         82.7217,  39.0515,  40.7402,  79.1892,  22.4108,  89.2846, 136.3947,
         65.3743, 103.5925,  95.5447,  81.5926,  12.6634,  63.6040,  62.0426,
        205.5912, 101.9656, 107.0903,  71.8776,  29.0691, 147.5957, 143.6247,
         22.7526,  37.3284, 111.6235, 105.9887,   8.1278,  27.0654,  15.9383,
         10.3872,  45.1840,  76.3380,  21.7799,  58.7372,  49.4186,  25.4217,
         27.0957,  66.1049, 173.9710,  28.3113,  77.2165, 325.8484, 106.9686,
         15.7200,  84.1854, 107.1475, 273.3094,  38.6473,  14.9391,  17.8697,
         40.8085,  11.1832,  40.8902,  20.9551, 116.9373,   9.6291,  22.0030,
        190.1533, 234.5649,  21.2514,  76.0506,  81.9858,  10.6095,  42.2503,
         91.3709,  19.7282, 112.0960, 121.7909,  14.1886,  58.3865,  52.6402,
         17.2470,  57.6114,  42.8738, 110.1691,  27.6537,  52.98

tensor([ 31.4925, 253.1786, 211.0279,  76.7009,  99.4347,  67.6709,  54.4654,
         80.8611,  43.1593,  22.2878,  37.8511,  23.6370,  35.2221,  13.5759,
         15.2027,  58.8448,  42.5569,  11.6867,  36.1502, 177.7305, 122.5365,
         49.1092,  13.9643,  18.3928,  65.2769,  35.6433,  41.7867,  44.4071,
         21.3576,  11.7826,  54.7446, 123.3898,  41.4587,  10.8692,  17.7383,
        149.2192,  11.1990,  25.4198,  70.2100,  40.5989,  37.3104, 140.5995,
         15.2730,  69.5467, 192.9838, 106.0981,  45.3705,  19.5891,  42.2087,
         21.4560,  15.1471,  60.4988,  91.9491,  24.8644,  38.7576,  18.0163,
         79.6872, 103.7400,  49.7002, 186.9333, 291.7184,  87.6857, 141.3891,
         35.3191, 417.7748,  22.9693,  97.1502,  94.9297,  48.5321, 164.9004,
         83.8671,  60.8736, 136.3755,  12.2333,   5.6230,  15.2232, 158.2439,
        194.5856,  37.0359,  14.0731,  17.7391, 103.1477,  17.9714, 232.4263,
        125.7354,  68.7708,  18.0184,   7.9680,  68.4399,  10.22

tensor([122.2266,  24.2952,  61.0811,  97.6872,  65.2229, 131.5623, 171.4599,
         37.7797,  28.2934,  31.2528,  55.3149, 123.2271,  64.7137,  52.0051,
         19.5880,  40.8210,  36.8589,  49.7980,  19.7233,  27.1068,  45.8752,
         48.5418,  12.8188,  96.9431,  57.1710,  10.5840, 135.6560, 133.8604,
         77.0538,  38.7829,  48.8188,  14.8982,  53.3898, 143.6879,  17.4633,
        356.6691,  83.9087,  20.3385,  23.7801, 151.3282,  12.6689, 167.6961,
        148.0078, 201.2280,  24.2125,  20.7604,  80.3337,  41.5894,  43.8999,
        159.9979,  17.8268,  31.0963,  12.2612,  41.4743,  71.1912,  16.0844,
         26.7936,  68.3891, 147.1812,  23.0480,  20.7830, 116.3075,  86.3750,
         39.3478,  22.8362,  63.1124,  40.0746,  78.5750,  16.7335, 156.3997,
         23.8802,  14.6448, 123.4060, 231.9187,  62.3685,  30.2923,  19.7979,
         55.8512,  17.5016,  33.7548,  30.0972,  47.4122,  21.0313, 117.2784,
         54.1655,  25.2359,  49.6723, 238.6639,  54.3761, 151.21

tensor([ 59.4164,  96.5561,  29.3585,  22.3960, 196.7226,  32.7350,  65.0860,
        137.9587,  38.7390,  88.1264,  30.8997,  20.6113, 124.0883,  59.1038,
        157.3666,  16.0857,   9.9991, 170.9859,  80.9465, 214.6813,  81.0316,
         39.2333,  98.3844,  33.1667,  29.0322,  30.5148,  89.0309,  48.2656,
         83.5458,  17.8197, 126.1231,  22.2621, 146.4876,  22.5202,  47.4733,
         61.7131,  30.9804,  55.7221,  53.4821,  47.6161,  74.7138,  48.3513,
         46.9047,  82.5305,  20.9113,  72.1165,  80.2444,  43.7673, 114.4124,
          6.7697,  26.4241, 112.4037,  16.3655,  21.7269,  76.3140,  83.9228,
         43.4169,  19.5328,  42.6523, 116.8988,  25.2413,  35.4759,  17.4714,
         23.4787, 126.1195,  16.4553,  53.2833, 114.4490, 133.3982,  16.2711,
         33.3216,  32.7225,  17.9677,  48.1796, 162.4162,  58.4762,  17.0635,
        219.1526,  55.1319,   9.1026, 151.8567, 121.2887, 105.1678,  17.0764,
        110.7616, 118.8220,  14.3900, 163.2382,  27.3859,  40.67

tensor([ 15.4038,  43.8778,  23.8640,  62.9754,  14.4090,  48.0234,  28.7870,
        154.2892, 123.7443,  17.5758,  36.1892,  54.5014,  58.5075,  13.7613,
         41.3109,  42.0984,  16.0024,  16.1300,  72.2207,  93.6271,  82.7730,
        126.8455, 105.1076,  60.9112, 134.0942,  43.2834,  13.0652,  27.6366,
        172.0035,  89.0378,  99.3463,  28.6724,  10.7678,  38.0566, 100.6663,
         33.4391,  25.2018,  20.8133,  10.0917,  18.5878,  84.2857,  50.1651,
         12.4599, 175.6026, 100.2547,  22.2143,  37.5086,  87.0411,  34.6550,
         88.7893, 119.6399,  11.2150,  45.5738,  88.4040,  63.0713,  11.8613,
         26.8936,  44.1966,  20.6455, 177.3728,  21.8268,  59.0550,  76.2251,
        118.9737,  89.7987,  33.5503,  46.0236, 139.0973,  17.5819, 121.6331,
         17.7994,  32.6871,  81.5133,  61.3002,  11.8973,  63.1123,  58.5455,
        103.1195,  30.2659,  50.9289,  69.1304,  86.6963,  68.8365,  65.1348,
         31.5539,  13.8996,  59.3284,  36.4875,  14.8409,  16.23

tensor([ 66.4852,  73.2652,  80.5930,  63.3315,  82.6400,  82.6550,  90.5392,
         14.1949,  43.4549,  68.8357,  38.0536,  76.5392,  32.1259,  76.1832,
         30.4117, 141.9323, 123.9281,  31.1896,   9.1284, 105.3585, 160.0286,
         69.0499,  48.2546,   5.5838,   9.4513, 159.5209,  32.9498,  48.4514,
         36.2661,  23.8757,  41.0800,  27.9068,  19.8419,  32.5743,  20.6043,
         69.2343,  18.7141,  38.1970,  91.1789,  38.4597,  25.2933, 102.4654,
         15.6062,  27.4808,  79.1355,  50.6948, 203.8867,  14.8571,  52.6532,
         16.8226,  86.7326,  77.0840,  31.9685,  71.3769,  30.1264,  51.5385,
        168.5518,  13.1219,  14.6209, 186.1901,  38.5119,  61.3286,  54.7493,
         54.5255,  52.3545,  70.2866,  96.3731,  44.7762,  79.9790,  89.2949,
         24.3707,  11.8781,  23.8375,  43.0915,  22.8047,  21.5869,  20.4238,
         91.8030,  48.9255, 245.0200,  35.9766,  22.8822,  28.8193,  51.5511,
        133.1364,  58.6187,  72.5093, 106.4989,  89.5721,  54.19

tensor([207.7793,  37.9687,  92.6993,  49.0449,  26.3941, 110.7983,  42.6238,
         17.4914,  10.5087,  29.6992,  64.5622,  29.3176,  30.1098, 144.6065,
         67.3060,  36.9077, 150.4455,  43.2993,  23.6387,  55.0622,  21.8157,
         28.0196,  26.2924,  42.4895,  54.8088,  62.4685,  52.2847, 127.0322,
         15.6720,  17.9725, 110.2190,  79.6105, 159.8601,  43.7984,  11.8108,
         65.9383,  44.5277, 230.2999,  73.5781,  78.5354,  10.2789,  12.3408,
        123.6986,  61.9494,  50.7919,  21.1373, 197.1941,  63.5889,  24.6796,
         59.9781,  25.7355,  49.5463,  22.0757,  58.8829,  41.2793, 161.9796,
         17.8588,  88.5753, 193.7728, 131.5060,  13.8132,  14.9877,  72.3066,
         82.5423,  23.4823,  14.8317, 297.3674, 126.3236,  27.9847,  13.3292,
        129.2988,  31.3680, 131.1676,  69.2791,  85.7290, 161.7613,  87.2326,
         65.3505,  50.2274, 221.6565,  17.3548,  30.2670, 138.6572,  23.8608,
         70.6559,  15.5152,  26.8182,  59.1996,  90.0030,  41.09

tensor([ 55.1756,  82.3140, 113.8604,  30.1269,  15.0897, 109.8294,  46.1077,
         17.3454,  88.1145, 111.9029,  50.5576,  28.0969,  14.6297,  35.1695,
         30.4423,  21.4298,  26.7662,  42.4525, 211.4887,  25.3471,  16.8052,
         99.7463, 168.6556,  57.3413,  70.9248, 174.8118,  10.6302,  15.3891,
         64.9514,  12.9221,  72.5785,   7.9959,  17.4937,  20.5974,   8.0955,
         27.9006,  55.5339,  32.1577,  47.9673,  93.2209,  22.1527,  24.1329,
         30.3567,  23.0540,  47.5323,  18.7745,  24.3195, 149.0462,  23.4638,
        152.7853, 100.3891,  77.9044, 125.7392,  61.0245,  29.3353,  17.3670,
         61.2215,  29.6639,  24.3167, 128.6917, 126.7151,  20.9448,  14.9323,
         21.8155,  27.5986, 170.7095,  37.9934, 118.3204,  65.2578,  19.6366,
         81.7956,  47.4552,  67.6813, 115.4147,  52.8745,  73.1820, 108.3172,
          5.9102, 134.4963,  21.3317, 186.2573, 175.0479,  44.7876,  73.2718,
         83.4645,  87.0481,  15.2496, 216.9420,  15.0865,  18.63

tensor([ 83.1525,  39.3290,  89.5147,  77.0433,  22.1276,  14.7286,  36.2106,
         22.4638,  10.8099,  31.1688, 150.2072,  71.6228,  41.2517,  44.1277,
         22.9280,   7.6484,  35.0081,  11.5545,  33.5960,  33.6418,  72.7657,
         24.4091,  34.8869,  86.2157,  59.0606,  57.5687, 138.5396,  97.9251,
         58.0571,  54.3511, 115.8921, 184.2714,  66.4825, 216.4568,  19.1235,
          5.2480,  61.7100,  35.0134,  14.3765, 141.7836,  65.8639, 138.4902,
         81.1476, 162.5502, 264.9859,  77.4110,  77.8266,  16.9838,  41.2757,
         24.8088,  13.8895,  74.0809,  52.8996,  30.6800,  11.5787,  17.5191,
         36.1066,  10.3610,  27.7859,   9.0549,  21.6615,  24.1262,  12.9075,
         26.8930, 159.9944,  18.6260,  74.9965,  15.9014,  43.2893,  73.3492,
         67.7907,  17.2197,  20.9746, 115.1467,  21.1385,  25.2532, 122.6641,
         33.2495, 116.9455,  90.9244,  29.4788,  88.8946,  30.0222,  37.0316,
         84.8059,  69.0031,  31.8376, 164.7195,  73.3339,  19.54

tensor([  9.5293,  41.4462, 133.5109,  38.7438,  91.9010,  30.9583,  19.4073,
        234.9658,  33.7486,  32.5353,  75.1034,  21.3079,  13.0784,  15.8783,
         31.9973,  26.1363,  99.1944,  47.1929,  80.7571,  58.6143, 186.7939,
         18.9430,  12.2516,  45.2752,  23.7239,  74.3860,  18.5801, 142.2322,
        104.0914, 165.7477,  21.1872,   9.9267,  29.0132,  16.9213,   9.2140,
         15.6385,  45.5239,  47.6594,  42.1188,  23.2342,  34.3763, 177.9339,
         12.5089,  17.5543,  55.1913,  80.4915,  58.7098,  24.2996,  15.1843,
         16.1385,  20.1830, 111.2806,  14.6715,  30.1397, 142.1276,  67.9336,
         94.6794,   7.7505,  43.5028,  39.1919,  20.7348,  20.8197,  37.0312,
        196.4277, 178.5278,  85.1437,  60.8750,  11.1624,  51.2856,  68.1519,
         22.5987,  27.6645,  14.6818,  17.5218,  89.0921, 127.9376,  19.2780,
         19.0803, 116.7307, 168.4431,  49.5923,  40.2006,  84.4826, 101.4225,
        177.3055, 206.5438,  94.7486,  80.2169,  12.6342,  62.95

In [22]:
leave_k_eval(model, tr, val, leavek=1, K=5)

{'avghit': 0.6173351010938017,
 'precision': 0.6173351010938017,
 'map': 0.40631698154900026,
 'ndcg': 0.45879305542103144}

In [42]:
qed = []
import models.ae
importlib.reload(models.ae)
model = models.ae.MultiVAE(best_m['dim'] + [n_items], dropout=best_m['dropout'])
importlib.reload(models.ae)
import neuralsort.neuralobjs

use_vae=True
loader = DataLoader(ae_dataset, batch_size=batch_size, shuffle=True, num_workers=4)
model = models.ae.MultiVAE(best_m['dim'] + [n_items], dropout=best_m['dropout'])
model.cuda()
optimizer = torch.optim.Adam(model.parameters(), lr=best_m['lr'])
lm = -1
update_count = 0
tr_t = {
    'l': [],
    ('precision', 5):[],
    ('precision', 10):[],
    ('map', 5): [],
    ('map', 10): [],
    ('ndcg', 5): [],
    ('ndcg', 10): [] ,
}
val_t = {
    'l': [],
    ('precision', 5):[],
    ('precision', 10):[],
    ('map', 5): [],
    ('map', 10): [],
    ('ndcg', 5): [],
    ('ndcg', 10): [] ,
}
te_t = {
    'l': [],
    ('precision', 5):[],
    ('precision', 10):[],
    ('map', 5): [],
    ('map', 10): [],
    ('ndcg', 5): [],
    ('ndcg', 10): [] ,
}
for epoch in (range(1, 1000 + 1)):
    model = model.train()
    model.training = True
    tr_losses = []
    # train for one epoch
    for uid, rowl in (loader):
        row = rowl.float().cuda()
        uid = uid.cuda() 
        loss = None 
        scores, mu, logvar = model.forward(row)
        if total_anneal_steps > 0:
            anneal_cap = min(_anneal_cap, 1. * update_count / total_anneal_steps)
        else:
            anneal_cap = _anneal_cap
        loss  = models.ae.loss_function(scores, row, mu, logvar)
        update_count += 1
        (loss.mean()).backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5)
        tr_losses.append(loss.detach().unsqueeze(-1)) 
        optimizer.step()
    
    if (epoch % 20 == 0):
        model.eval()
        model.training=False
        tr_loss = float(torch.cat(tr_losses).mean().detach().cpu().numpy())
        vad_scores, mu, logvar = model.forward(vin_dense)
        vad_loss = models.ae.loss_function(vad_scores, vin_dense, mu, logvar, anneal_cap)
        vad_loss = float(vad_loss.mean().detach().cpu().numpy())
        te_scores, mu, logvar = model.forward(tin_dense)
        te_loss = models.ae.loss_function(te_scores, tin_dense, mu, logvar, anneal_cap)
        te_loss = float(te_loss.mean().detach().cpu().numpy())

        tr_t['l'].append(tr_loss)
        val_t['l'].append(vad_loss)
        te_t['l'].append(te_loss)
        wrapper = models.ae.implicitWrapper(model, naive_sparse2tensor, vae=True)
        ret = (tr_loss, vad_loss)

        for store, q, a in  zip([tr_t, val_t, te_t], [trin, vin, tin], [trte, vo, to]):
            for topk in [5, 10]:
                scs = ranking_metrics_at_k(wrapper, q, a, K=topk, num_threads=4)
                for ty in ['map', 'precision', 'ndcg']:
                    store[(ty, topk)].append(scs[ty])
            print(store)
        qed.append(ret)
no_add = qed

{'l': [289.5909423828125], ('precision', 5): [0.11661874640597812], ('precision', 10): [0.09051178838412861], ('map', 5): [0.08760877899175729], ('map', 10): [0.07431090429697304], ('ndcg', 5): [0.1408258883110016], ('ndcg', 10): [0.14093437733598943]}
{'l': [227.49560546875], ('precision', 5): [0.10240000000000052], ('precision', 10): [0.0801], ('map', 5): [0.07979027777777789], ('map', 10): [0.06817714962836993], ('ndcg', 5): [0.12668102304479953], ('ndcg', 10): [0.12857793567911105]}
{'l': [217.5330352783203], ('precision', 5): [0.09760000000000048], ('precision', 10): [0.07919999999999996], ('map', 5): [0.08259361111111112], ('map', 10): [0.07535227040816322], ('ndcg', 5): [0.12888342095491465], ('ndcg', 10): [0.1372432495542677]}
{'l': [289.5909423828125, 282.6343994140625], ('precision', 5): [0.11661874640597812, 0.14249568717653538], ('precision', 10): [0.09051178838412861, 0.11000575043128286], ('map', 5): [0.08760877899175729, 0.11359409941856713], ('map', 10): [0.074310904296

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812], ('precision', 5): [0.10240000000000052, 0.12940000000000063, 0.13860000000000033, 0.14480000000000023, 0.15060000000000018, 0.15300000000000008], ('precision', 10): [0.0801, 0.09879999999999979, 0.11279999999999975, 0.11819999999999958, 0.12269999999999964, 0.12609999999999957], ('map', 5): [0.07979027777777789, 0.10221972222222232, 0.11133083333333343, 0.11578083333333335, 0.12177249999999999, 0.12651111111111119], ('map', 10): [0.06817714962836993, 0.08694477812421274, 0.0984474332325523, 0.10310245354623332, 0.1084870249118166, 0.11340036029226509], ('ndcg', 5): [0.12668102304479953, 0.16003499257847076, 0.1722412752772343, 0.17852601156579612, 0.18584322767898317, 0.19150194941408372], ('ndcg', 10): [0.12857793567911105, 0.15894725213487954, 0.1775323667095789, 0.18577447167452246, 0.19406701399502402, 0.20127833998610503]}
{'l': [217.5330352783203, 209.7557983

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152961472110233, 0.1679125934445072, 0.1728004600345016, 0.17642323174238014, 0.1809085681426103, 0.18355376653248948], ('precision', 10): [0.09051178838412861, 0.11000575043128286, 0.1218228867165047, 0.12829212190914435, 0.13326624496837391, 0.1369177688326638, 0.1396492236917782, 0.14229442208165735, 0.14468085106383097], ('map', 5): [0.08760877899175729, 0.11359409941856713, 0.1270865280173789, 0.132915867995655, 0.1382136924158199, 0.14260821992204956, 0.14691712989585304, 0.14990216280109875, 0.1529458181585839], ('map', 10): [0.07431090429697304, 0.0961155461348596, 0.10852501926590045, 0.11496247305707767, 0.1199610208250658, 0.12392526332780882, 0.12764893792692641, 0.13034509945065914, 0.1330272191246099], ('ndcg

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152961472110233, 0.1679125934445072, 0.1728004600345016, 0.17642323174238014, 0.1809085681426103, 0.18355376653248948, 0.18430132259919457, 0.18752156411730883], ('precision', 10): [0.09051178838412861, 0.11000575043128286, 0.1218228867165047, 0.12829212190914435, 0.13326624496837391, 0.1369177688326638, 0.1396492236917782, 0.14229442208165735, 0.14468085106383097, 0.14695227142035797, 0.1487636572742972], ('map', 5): [0.08760877899175729, 0.11359409941856713, 0.1270865280173789, 0.132915867995655, 0.1382136924158199, 0.14260821992204956, 0.14691712989585304, 0.14990216280109875, 0.1529458181585839, 0.15342446169573817, 0.15649750814644423], ('map', 10): [0.07431090429697304, 0.0961155

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999], ('precision', 10): [0.07919999999999996, 0.09629999999999969, 0.10849999999999968, 0.11379999999999957, 0.11759999999999954, 0.11989999999999966, 0.12109999999999968, 0.12259999999999965, 0.12469999999999955, 0.1250999999999996, 0.12669999999999956, 0.12629999999999958], ('map', 5): [0.08259361111111112, 0.10588777777777775, 0.11556694444444443, 0.1210824999999999, 0.12333111111111102, 0.1279930555555555, 0.1303272222222221, 0.13357944444444442, 0.13526888888888877, 0.13585555555555548, 0.13614472222222215, 0.137

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375], ('precision', 5): [0.10240000000000052, 0.12940000000000063, 0.13860000000000033, 0.14480000000000023, 0.15060000000000018, 0.15300000000000008, 0.15719999999999987, 0.15939999999999985, 0.16139999999999968, 0.16419999999999965, 0.1647999999999996, 0.16619999999999963, 0.16659999999999967, 0.1663999999999996], ('precision', 10): [0.0801, 0.09879999999999979, 0.11279999999999975, 0.11819999999999958, 0.12269999999999964, 0.12609999999999957, 0.12769999999999956, 0.12869999999999948, 0.13029999999999944, 0.13149999999999937, 0.13079999999999944, 0.1311999999999994, 0.13239999999999932, 0.1314999999999993], ('map', 5): [0.07979027777777789, 0.10221972222222232, 0.11133083333333343, 0.11578083333333335, 0.121772499999

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991], ('precision', 10): [0.07919999999999996, 0.09629999999999969, 0.10849999999999968, 0.11379999999999957, 0.11759999999999954, 0.11989999999999966, 0.12109999999999968, 0.12259999999999965, 0.12469999999999955, 0.1250999999999996, 0.12669999999999956, 0.12629999999999958, 0.12729999999999964, 0.1278999999999996, 0.1283999999999996], ('map', 5): [0.08259361111111112, 0.10588777777777775, 0.1155669

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594, 265.80865478515625, 265.8110656738281, 265.00244140625, 265.22613525390625, 262.9532165527344, 262.597412109375], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152961472110233, 0.1679125934445072, 0.1728004600345016, 0.17642323174238014, 0.1809085681426103, 0.18355376653248948, 0.18430132259919457, 0.18752156411730883, 0.1887291546866016, 0.1913168487636575, 0.1947096032202418, 0.19689476710753342, 0.19844738355376726, 0.2002300172512947], ('precision', 10): [0.09051178838412861, 0.11000575043128286, 0.1218228867165047, 0.12829212190914435, 0.13326624496837391, 0.1369177688326638, 0.1396492236917782, 0.14229442208165735, 0.14468085106383097, 0.14695227142035797, 0.1487636572742972, 0.15117883841288263, 0.15250143760782245, 0.154169

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375, 205.3716583251953, 205.17185974121094, 204.96006774902344, 204.8592529296875], ('precision', 5): [0.10240000000000052, 0.12940000000000063, 0.13860000000000033, 0.14480000000000023, 0.15060000000000018, 0.15300000000000008, 0.15719999999999987, 0.15939999999999985, 0.16139999999999968, 0.16419999999999965, 0.1647999999999996, 0.16619999999999963, 0.16659999999999967, 0.1663999999999996, 0.16659999999999964, 0.16699999999999962, 0.16619999999999963, 0.16819999999999968], ('precision', 10): [0.0801, 0.09879999999999979, 0.11279999999999975, 0.11819999999999958, 0.12269999999999964, 0.12609999999999957, 0.12769999999999956, 0.12869999999999948, 0.13029999999999944, 0.13149999999999937, 0.13079999999999944, 0.131199999

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.16139999999999988, 0.16299999999999987], ('precision', 10): [0.07919999999999996, 0.09629999999999969, 0.10849999999999968, 0.11379999999999957, 0.11759999999999954, 0.11989999999999966, 0.12109999999999968, 0.12259999999999965, 0.12469999999999955, 0.1250999999999996, 0.1266

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.16139999999999988, 0.16299999999999987, 0.16139999999999988], ('precision', 10): [0.07919999999999996, 0.09629999999999969, 0.10849999999999968, 0.11379999999999957, 0.11759999999999954, 0.11989999999999966, 0.12109999999999968, 0.12259999999999965, 0.1246

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.16139999999999988, 0.16299999999999987, 0.16139999999999988, 0.16119999999999987], ('precision', 10): [0.07919999999999996, 0.09629999999999969, 0.10849999999999968, 0.11379999999999957, 0.11759999999999954, 0.11989999999999966, 0.121099

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.16139999999999988, 0.16299999999999987, 0.16139999999999988, 0.16119999999999987, 0.16099999999999992], ('precision', 10): [0.07919999999999996, 0.09629999999999969, 0.10849999999999968, 0.11379999999999957, 0.1175999

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.16139999999999988, 0.16299999999999987, 0.16139999999999988, 0.16119999999999987, 0.16099999999999992, 0.16079999999999992], ('precision', 10): [0.07919999999999996, 0.09629999999999969, 0.10849999

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.16139999999999988, 0.16299999999999987, 0.16139999999999988, 0.16119999999999987, 0.16099999999999992, 0.16079999999999992, 0.16159999999999994], ('precision', 10): [0.079199999

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.16139999999999988, 0.16299999999999987, 0.16139999999999988, 0.16119999999999987, 0.16099999999999992, 0.16079999999999992, 0.16159999999999994, 0.1606], ('p

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.16139999999999988, 0.16299999999999987, 0.16139999999999988, 0.16119999999999987, 0.16099999999999992, 0.16079999999999992, 0.16159999999

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.16139999999999988, 0.16299999999999987, 0.16139999999999988, 0.16119999999999987, 0.16099999999999992, 0.160799999999

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156, 194.7155303955078], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.16139999999999988, 0.16299999999999987, 0.16139999999999988, 0.16119999999999987, 0.16099999999999

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375, 205.3716583251953, 205.17185974121094, 204.96006774902344, 204.8592529296875, 204.688720703125, 204.54920959472656, 204.43365478515625, 204.29794311523438, 204.27822875976562, 204.2465057373047, 204.07785034179688, 204.11155700683594, 203.9482879638672, 203.95773315429688, 203.96775817871094], ('precision', 5): [0.10240000000000052, 0.12940000000000063, 0.13860000000000033, 0.14480000000000023, 0.15060000000000018, 0.15300000000000008, 0.15719999999999987, 0.15939999999999985, 0.16139999999999968, 0.16419999999999965, 0.1647999999999996, 0.16619999999999963, 0.16659999999999967, 0.1663999999999996, 0.16659999999999964, 0.16699999999999962, 0.16619999999999963, 0.16819999999999968, 0.1673999999999996, 0.166199999999

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594, 265.80865478515625, 265.8110656738281, 265.00244140625, 265.22613525390625, 262.9532165527344, 262.597412109375, 263.26336669921875, 262.4729309082031, 263.3291320800781, 262.25579833984375, 260.999755859375, 260.1268005371094, 260.2434997558594, 261.2622375488281, 260.0489807128906, 259.48114013671875, 259.8913269042969, 259.4231872558594, 259.11285400390625], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152961472110233, 0.1679125934445072, 0.1728004600345016, 0.17642323174238014, 0.1809085681426103, 0.18355376653248948, 0.18430132259919457, 0.18752156411730883, 0.1887291546866016, 0.1913168487636575, 0.1947096032202418, 0.19689476710753342, 0.19844738355376726, 0.2002300172512947, 0.2013801035077637, 0.20327774583093805, 0.20494

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156, 194.7155303955078, 194.7046661376953, 194.66481018066406], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.16139999999999988, 0.16299999999999987, 0.16139999999999988

In [43]:
for epoch in (range(1, 400 + 1)):
    model = model.train()
    model.training = True
    tr_losses = []
    # train for one epoch
    for uid, rowl in (loader):
        row = rowl.float().cuda()
        uid = uid.cuda() 
        loss = None 
        scores, mu, logvar = model.forward(row)
        if total_anneal_steps > 0:
            anneal_cap = min(_anneal_cap, 1. * update_count / total_anneal_steps)
        else:
            anneal_cap = _anneal_cap
        loss  = models.ae.loss_function(scores, row, mu, logvar)
        update_count += 1
        (loss.mean()).backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5)
        tr_losses.append(loss.detach().unsqueeze(-1)) 
        optimizer.step()
    
    if (epoch % 20 == 0):
        model.eval()
        model.training=False
        tr_loss = float(torch.cat(tr_losses).mean().detach().cpu().numpy())
        vad_scores, mu, logvar = model.forward(vin_dense)
        vad_loss = models.ae.loss_function(vad_scores, vin_dense, mu, logvar, anneal_cap)
        vad_loss = float(vad_loss.mean().detach().cpu().numpy())
        te_scores, mu, logvar = model.forward(tin_dense)
        te_loss = models.ae.loss_function(te_scores, tin_dense, mu, logvar, anneal_cap)
        te_loss = float(te_loss.mean().detach().cpu().numpy())

        tr_t['l'].append(tr_loss)
        val_t['l'].append(vad_loss)
        te_t['l'].append(te_loss)
        wrapper = models.ae.implicitWrapper(model, naive_sparse2tensor, vae=True)
        ret = (tr_loss, vad_loss)

        for store, q, a in  zip([tr_t, val_t, te_t], [trin, vin, tin], [trte, vo, to]):
            for topk in [5, 10]:
                scs = ranking_metrics_at_k(wrapper, q, a, K=topk, num_threads=4)
                for ty in ['map', 'precision', 'ndcg']:
                    store[(ty, topk)].append(scs[ty])
            print(store)
        qed.append(ret)
no_add = qed

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594, 265.80865478515625, 265.8110656738281, 265.00244140625, 265.22613525390625, 262.9532165527344, 262.597412109375, 263.26336669921875, 262.4729309082031, 263.3291320800781, 262.25579833984375, 260.999755859375, 260.1268005371094, 260.2434997558594, 261.2622375488281, 260.0489807128906, 259.48114013671875, 259.8913269042969, 259.4231872558594, 259.11285400390625, 259.15362548828125], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152961472110233, 0.1679125934445072, 0.1728004600345016, 0.17642323174238014, 0.1809085681426103, 0.18355376653248948, 0.18430132259919457, 0.18752156411730883, 0.1887291546866016, 0.1913168487636575, 0.1947096032202418, 0.19689476710753342, 0.19844738355376726, 0.2002300172512947, 0.2013801035077637, 0.203277

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156, 194.7155303955078, 194.7046661376953, 194.66481018066406, 194.5948486328125], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.16139999999999988, 0.16299999999999987, 

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375, 205.3716583251953, 205.17185974121094, 204.96006774902344, 204.8592529296875, 204.688720703125, 204.54920959472656, 204.43365478515625, 204.29794311523438, 204.27822875976562, 204.2465057373047, 204.07785034179688, 204.11155700683594, 203.9482879638672, 203.95773315429688, 203.96775817871094, 203.90040588378906, 203.8463897705078, 203.96859741210938], ('precision', 5): [0.10240000000000052, 0.12940000000000063, 0.13860000000000033, 0.14480000000000023, 0.15060000000000018, 0.15300000000000008, 0.15719999999999987, 0.15939999999999985, 0.16139999999999968, 0.16419999999999965, 0.1647999999999996, 0.16619999999999963, 0.16659999999999967, 0.1663999999999996, 0.16659999999999964, 0.16699999999999962, 0.166199999999999

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594, 265.80865478515625, 265.8110656738281, 265.00244140625, 265.22613525390625, 262.9532165527344, 262.597412109375, 263.26336669921875, 262.4729309082031, 263.3291320800781, 262.25579833984375, 260.999755859375, 260.1268005371094, 260.2434997558594, 261.2622375488281, 260.0489807128906, 259.48114013671875, 259.8913269042969, 259.4231872558594, 259.11285400390625, 259.15362548828125, 259.3638916015625, 258.65191650390625], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152961472110233, 0.1679125934445072, 0.1728004600345016, 0.17642323174238014, 0.1809085681426103, 0.18355376653248948, 0.18430132259919457, 0.18752156411730883, 0.1887291546866016, 0.1913168487636575, 0.1947096032202418, 0.19689476710753342, 0.19844738355376726, 0.2002300

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156, 194.7155303955078, 194.7046661376953, 194.66481018066406, 194.5948486328125, 194.69700622558594, 194.78758239746094], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.1599999999999999, 0.16099999999999984, 0.

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375, 205.3716583251953, 205.17185974121094, 204.96006774902344, 204.8592529296875, 204.688720703125, 204.54920959472656, 204.43365478515625, 204.29794311523438, 204.27822875976562, 204.2465057373047, 204.07785034179688, 204.11155700683594, 203.9482879638672, 203.95773315429688, 203.96775817871094, 203.90040588378906, 203.8463897705078, 203.96859741210938, 204.056640625, 203.8594207763672], ('precision', 5): [0.10240000000000052, 0.12940000000000063, 0.13860000000000033, 0.14480000000000023, 0.15060000000000018, 0.15300000000000008, 0.15719999999999987, 0.15939999999999985, 0.16139999999999968, 0.16419999999999965, 0.1647999999999996, 0.16619999999999963, 0.16659999999999967, 0.1663999999999996, 0.16659999999999964, 0.16

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594, 265.80865478515625, 265.8110656738281, 265.00244140625, 265.22613525390625, 262.9532165527344, 262.597412109375, 263.26336669921875, 262.4729309082031, 263.3291320800781, 262.25579833984375, 260.999755859375, 260.1268005371094, 260.2434997558594, 261.2622375488281, 260.0489807128906, 259.48114013671875, 259.8913269042969, 259.4231872558594, 259.11285400390625, 259.15362548828125, 259.3638916015625, 258.65191650390625, 258.1945495605469, 258.20001220703125], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152961472110233, 0.1679125934445072, 0.1728004600345016, 0.17642323174238014, 0.1809085681426103, 0.18355376653248948, 0.18430132259919457, 0.18752156411730883, 0.1887291546866016, 0.1913168487636575, 0.1947096032202418, 0.1968947671

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156, 194.7155303955078, 194.7046661376953, 194.66481018066406, 194.5948486328125, 194.69700622558594, 194.78758239746094, 194.6175079345703, 194.4956512451172], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.1577999999999999, 0.15979999999999991, 0.159

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375, 205.3716583251953, 205.17185974121094, 204.96006774902344, 204.8592529296875, 204.688720703125, 204.54920959472656, 204.43365478515625, 204.29794311523438, 204.27822875976562, 204.2465057373047, 204.07785034179688, 204.11155700683594, 203.9482879638672, 203.95773315429688, 203.96775817871094, 203.90040588378906, 203.8463897705078, 203.96859741210938, 204.056640625, 203.8594207763672, 203.73776245117188, 203.67031860351562], ('precision', 5): [0.10240000000000052, 0.12940000000000063, 0.13860000000000033, 0.14480000000000023, 0.15060000000000018, 0.15300000000000008, 0.15719999999999987, 0.15939999999999985, 0.16139999999999968, 0.16419999999999965, 0.1647999999999996, 0.16619999999999963, 0.16659999999999967, 0.166

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594, 265.80865478515625, 265.8110656738281, 265.00244140625, 265.22613525390625, 262.9532165527344, 262.597412109375, 263.26336669921875, 262.4729309082031, 263.3291320800781, 262.25579833984375, 260.999755859375, 260.1268005371094, 260.2434997558594, 261.2622375488281, 260.0489807128906, 259.48114013671875, 259.8913269042969, 259.4231872558594, 259.11285400390625, 259.15362548828125, 259.3638916015625, 258.65191650390625, 258.1945495605469, 258.20001220703125, 259.23175048828125, 257.7560729980469], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152961472110233, 0.1679125934445072, 0.1728004600345016, 0.17642323174238014, 0.1809085681426103, 0.18355376653248948, 0.18430132259919457, 0.18752156411730883, 0.1887291546866016, 0.19131684876

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156, 194.7155303955078, 194.7046661376953, 194.66481018066406, 194.5948486328125, 194.69700622558594, 194.78758239746094, 194.6175079345703, 194.4956512451172, 194.40553283691406, 194.2350311279297], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.1599999999999999, 0.1595999999999999, 0.15779

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375, 205.3716583251953, 205.17185974121094, 204.96006774902344, 204.8592529296875, 204.688720703125, 204.54920959472656, 204.43365478515625, 204.29794311523438, 204.27822875976562, 204.2465057373047, 204.07785034179688, 204.11155700683594, 203.9482879638672, 203.95773315429688, 203.96775817871094, 203.90040588378906, 203.8463897705078, 203.96859741210938, 204.056640625, 203.8594207763672, 203.73776245117188, 203.67031860351562, 203.4450225830078, 203.45870971679688], ('precision', 5): [0.10240000000000052, 0.12940000000000063, 0.13860000000000033, 0.14480000000000023, 0.15060000000000018, 0.15300000000000008, 0.15719999999999987, 0.15939999999999985, 0.16139999999999968, 0.16419999999999965, 0.1647999999999996, 0.166199

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594, 265.80865478515625, 265.8110656738281, 265.00244140625, 265.22613525390625, 262.9532165527344, 262.597412109375, 263.26336669921875, 262.4729309082031, 263.3291320800781, 262.25579833984375, 260.999755859375, 260.1268005371094, 260.2434997558594, 261.2622375488281, 260.0489807128906, 259.48114013671875, 259.8913269042969, 259.4231872558594, 259.11285400390625, 259.15362548828125, 259.3638916015625, 258.65191650390625, 258.1945495605469, 258.20001220703125, 259.23175048828125, 257.7560729980469, 257.4389953613281, 256.48321533203125], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152961472110233, 0.1679125934445072, 0.1728004600345016, 0.17642323174238014, 0.1809085681426103, 0.18355376653248948, 0.18430132259919457, 0.1875215641173

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156, 194.7155303955078, 194.7046661376953, 194.66481018066406, 194.5948486328125, 194.69700622558594, 194.78758239746094, 194.6175079345703, 194.4956512451172, 194.40553283691406, 194.2350311279297, 194.22576904296875, 194.03977966308594], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.15660000000000004, 0.158, 0.159, 0.15999

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375, 205.3716583251953, 205.17185974121094, 204.96006774902344, 204.8592529296875, 204.688720703125, 204.54920959472656, 204.43365478515625, 204.29794311523438, 204.27822875976562, 204.2465057373047, 204.07785034179688, 204.11155700683594, 203.9482879638672, 203.95773315429688, 203.96775817871094, 203.90040588378906, 203.8463897705078, 203.96859741210938, 204.056640625, 203.8594207763672, 203.73776245117188, 203.67031860351562, 203.4450225830078, 203.45870971679688, 203.27615356445312, 203.1498565673828], ('precision', 5): [0.10240000000000052, 0.12940000000000063, 0.13860000000000033, 0.14480000000000023, 0.15060000000000018, 0.15300000000000008, 0.15719999999999987, 0.15939999999999985, 0.16139999999999968, 0.16419999

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594, 265.80865478515625, 265.8110656738281, 265.00244140625, 265.22613525390625, 262.9532165527344, 262.597412109375, 263.26336669921875, 262.4729309082031, 263.3291320800781, 262.25579833984375, 260.999755859375, 260.1268005371094, 260.2434997558594, 261.2622375488281, 260.0489807128906, 259.48114013671875, 259.8913269042969, 259.4231872558594, 259.11285400390625, 259.15362548828125, 259.3638916015625, 258.65191650390625, 258.1945495605469, 258.20001220703125, 259.23175048828125, 257.7560729980469, 257.4389953613281, 256.48321533203125, 257.77520751953125, 256.35614013671875], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152961472110233, 0.1679125934445072, 0.1728004600345016, 0.17642323174238014, 0.1809085681426103, 0.183553766532489

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156, 194.7155303955078, 194.7046661376953, 194.66481018066406, 194.5948486328125, 194.69700622558594, 194.78758239746094, 194.6175079345703, 194.4956512451172, 194.40553283691406, 194.2350311279297, 194.22576904296875, 194.03977966308594, 193.91635131835938, 193.87876892089844], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.1526000000000001, 0.1564000000000001, 0.

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375, 205.3716583251953, 205.17185974121094, 204.96006774902344, 204.8592529296875, 204.688720703125, 204.54920959472656, 204.43365478515625, 204.29794311523438, 204.27822875976562, 204.2465057373047, 204.07785034179688, 204.11155700683594, 203.9482879638672, 203.95773315429688, 203.96775817871094, 203.90040588378906, 203.8463897705078, 203.96859741210938, 204.056640625, 203.8594207763672, 203.73776245117188, 203.67031860351562, 203.4450225830078, 203.45870971679688, 203.27615356445312, 203.1498565673828, 203.10812377929688, 202.8893280029297], ('precision', 5): [0.10240000000000052, 0.12940000000000063, 0.13860000000000033, 0.14480000000000023, 0.15060000000000018, 0.15300000000000008, 0.15719999999999987, 0.15939999999

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594, 265.80865478515625, 265.8110656738281, 265.00244140625, 265.22613525390625, 262.9532165527344, 262.597412109375, 263.26336669921875, 262.4729309082031, 263.3291320800781, 262.25579833984375, 260.999755859375, 260.1268005371094, 260.2434997558594, 261.2622375488281, 260.0489807128906, 259.48114013671875, 259.8913269042969, 259.4231872558594, 259.11285400390625, 259.15362548828125, 259.3638916015625, 258.65191650390625, 258.1945495605469, 258.20001220703125, 259.23175048828125, 257.7560729980469, 257.4389953613281, 256.48321533203125, 257.77520751953125, 256.35614013671875, 256.6065368652344, 257.4552917480469], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152961472110233, 0.1679125934445072, 0.1728004600345016, 0.17642323174238014,

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156, 194.7155303955078, 194.7046661376953, 194.66481018066406, 194.5948486328125, 194.69700622558594, 194.78758239746094, 194.6175079345703, 194.4956512451172, 194.40553283691406, 194.2350311279297, 194.22576904296875, 194.03977966308594, 193.91635131835938, 193.87876892089844, 193.68028259277344, 193.61415100097656], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14600000000000032, 0.15040000000000017, 0.

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375, 205.3716583251953, 205.17185974121094, 204.96006774902344, 204.8592529296875, 204.688720703125, 204.54920959472656, 204.43365478515625, 204.29794311523438, 204.27822875976562, 204.2465057373047, 204.07785034179688, 204.11155700683594, 203.9482879638672, 203.95773315429688, 203.96775817871094, 203.90040588378906, 203.8463897705078, 203.96859741210938, 204.056640625, 203.8594207763672, 203.73776245117188, 203.67031860351562, 203.4450225830078, 203.45870971679688, 203.27615356445312, 203.1498565673828, 203.10812377929688, 202.8893280029297, 202.84896850585938, 202.72108459472656], ('precision', 5): [0.10240000000000052, 0.12940000000000063, 0.13860000000000033, 0.14480000000000023, 0.15060000000000018, 0.1530000000000

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594, 265.80865478515625, 265.8110656738281, 265.00244140625, 265.22613525390625, 262.9532165527344, 262.597412109375, 263.26336669921875, 262.4729309082031, 263.3291320800781, 262.25579833984375, 260.999755859375, 260.1268005371094, 260.2434997558594, 261.2622375488281, 260.0489807128906, 259.48114013671875, 259.8913269042969, 259.4231872558594, 259.11285400390625, 259.15362548828125, 259.3638916015625, 258.65191650390625, 258.1945495605469, 258.20001220703125, 259.23175048828125, 257.7560729980469, 257.4389953613281, 256.48321533203125, 257.77520751953125, 256.35614013671875, 256.6065368652344, 257.4552917480469, 256.27496337890625, 256.626953125], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152961472110233, 0.1679125934445072, 0.172

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156, 194.7155303955078, 194.7046661376953, 194.66481018066406, 194.5948486328125, 194.69700622558594, 194.78758239746094, 194.6175079345703, 194.4956512451172, 194.40553283691406, 194.2350311279297, 194.22576904296875, 194.03977966308594, 193.91635131835938, 193.87876892089844, 193.68028259277344, 193.61415100097656, 193.49732971191406, 193.46051025390625], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.13320000000000054, 0.14160000000000036, 0.14

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375, 205.3716583251953, 205.17185974121094, 204.96006774902344, 204.8592529296875, 204.688720703125, 204.54920959472656, 204.43365478515625, 204.29794311523438, 204.27822875976562, 204.2465057373047, 204.07785034179688, 204.11155700683594, 203.9482879638672, 203.95773315429688, 203.96775817871094, 203.90040588378906, 203.8463897705078, 203.96859741210938, 204.056640625, 203.8594207763672, 203.73776245117188, 203.67031860351562, 203.4450225830078, 203.45870971679688, 203.27615356445312, 203.1498565673828, 203.10812377929688, 202.8893280029297, 202.84896850585938, 202.72108459472656, 202.71632385253906, 202.55117797851562], ('precision', 5): [0.10240000000000052, 0.12940000000000063, 0.13860000000000033, 0.144800000000000

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594, 265.80865478515625, 265.8110656738281, 265.00244140625, 265.22613525390625, 262.9532165527344, 262.597412109375, 263.26336669921875, 262.4729309082031, 263.3291320800781, 262.25579833984375, 260.999755859375, 260.1268005371094, 260.2434997558594, 261.2622375488281, 260.0489807128906, 259.48114013671875, 259.8913269042969, 259.4231872558594, 259.11285400390625, 259.15362548828125, 259.3638916015625, 258.65191650390625, 258.1945495605469, 258.20001220703125, 259.23175048828125, 257.7560729980469, 257.4389953613281, 256.48321533203125, 257.77520751953125, 256.35614013671875, 256.6065368652344, 257.4552917480469, 256.27496337890625, 256.626953125, 256.97039794921875, 256.0778503417969], ('precision', 5): [0.11661874640597812, 0.14249568717653538, 0.15606670500287304, 0.16152

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156, 194.7155303955078, 194.7046661376953, 194.66481018066406, 194.5948486328125, 194.69700622558594, 194.78758239746094, 194.6175079345703, 194.4956512451172, 194.40553283691406, 194.2350311279297, 194.22576904296875, 194.03977966308594, 193.91635131835938, 193.87876892089844, 193.68028259277344, 193.61415100097656, 193.49732971191406, 193.46051025390625, 193.30300903320312, 193.23477172851562], ('precision', 5): [0.09760000000000048, 0.12180000000000067, 0.1332

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375, 205.3716583251953, 205.17185974121094, 204.96006774902344, 204.8592529296875, 204.688720703125, 204.54920959472656, 204.43365478515625, 204.29794311523438, 204.27822875976562, 204.2465057373047, 204.07785034179688, 204.11155700683594, 203.9482879638672, 203.95773315429688, 203.96775817871094, 203.90040588378906, 203.8463897705078, 203.96859741210938, 204.056640625, 203.8594207763672, 203.73776245117188, 203.67031860351562, 203.4450225830078, 203.45870971679688, 203.27615356445312, 203.1498565673828, 203.10812377929688, 202.8893280029297, 202.84896850585938, 202.72108459472656, 202.71632385253906, 202.55117797851562, 202.4641571044922, 202.41143798828125], ('precision', 5): [0.10240000000000052, 0.12940000000000063,

{'l': [289.5909423828125, 282.6343994140625, 276.35833740234375, 273.54266357421875, 270.0124206542969, 270.3948669433594, 269.46160888671875, 268.6343994140625, 267.2833557128906, 267.1373596191406, 265.5999450683594, 265.80865478515625, 265.8110656738281, 265.00244140625, 265.22613525390625, 262.9532165527344, 262.597412109375, 263.26336669921875, 262.4729309082031, 263.3291320800781, 262.25579833984375, 260.999755859375, 260.1268005371094, 260.2434997558594, 261.2622375488281, 260.0489807128906, 259.48114013671875, 259.8913269042969, 259.4231872558594, 259.11285400390625, 259.15362548828125, 259.3638916015625, 258.65191650390625, 258.1945495605469, 258.20001220703125, 259.23175048828125, 257.7560729980469, 257.4389953613281, 256.48321533203125, 257.77520751953125, 256.35614013671875, 256.6065368652344, 257.4552917480469, 256.27496337890625, 256.626953125, 256.97039794921875, 256.0778503417969, 256.2647705078125, 256.3413391113281], ('precision', 5): [0.11661874640597812, 0.142495687

{'l': [217.5330352783203, 209.75579833984375, 205.34423828125, 202.57273864746094, 200.94711303710938, 199.9864959716797, 199.13650512695312, 198.41632080078125, 197.9143524169922, 197.4642333984375, 197.07662963867188, 196.75135803222656, 196.50357055664062, 196.24407958984375, 196.05755615234375, 195.85609436035156, 195.65623474121094, 195.54336547851562, 195.3961181640625, 195.27359008789062, 195.1609344482422, 195.06124877929688, 195.02476501464844, 194.98326110839844, 194.82798767089844, 194.86610412597656, 194.71986389160156, 194.7155303955078, 194.7046661376953, 194.66481018066406, 194.5948486328125, 194.69700622558594, 194.78758239746094, 194.6175079345703, 194.4956512451172, 194.40553283691406, 194.2350311279297, 194.22576904296875, 194.03977966308594, 193.91635131835938, 193.87876892089844, 193.68028259277344, 193.61415100097656, 193.49732971191406, 193.46051025390625, 193.30300903320312, 193.23477172851562, 193.17562866210938, 193.17103576660156], ('precision', 5): [0.097600

{'l': [227.49560546875, 219.5446014404297, 214.9517822265625, 212.13624572753906, 210.46603393554688, 209.47317504882812, 208.61630249023438, 207.87106323242188, 207.35023498535156, 206.86973571777344, 206.470703125, 206.1251220703125, 205.86764526367188, 205.58001708984375, 205.3716583251953, 205.17185974121094, 204.96006774902344, 204.8592529296875, 204.688720703125, 204.54920959472656, 204.43365478515625, 204.29794311523438, 204.27822875976562, 204.2465057373047, 204.07785034179688, 204.11155700683594, 203.9482879638672, 203.95773315429688, 203.96775817871094, 203.90040588378906, 203.8463897705078, 203.96859741210938, 204.056640625, 203.8594207763672, 203.73776245117188, 203.67031860351562, 203.4450225830078, 203.45870971679688, 203.27615356445312, 203.1498565673828, 203.10812377929688, 202.8893280029297, 202.84896850585938, 202.72108459472656, 202.71632385253906, 202.55117797851562, 202.4641571044922, 202.41143798828125, 202.42738342285156, 202.3318634033203], ('precision', 5): [0.

In [13]:
qed = []
import models.ae
importlib.reload(models.ae)
import neuralsort.neuralobjs
importlib.reload(models.ae)
use_vae=True
loader = DataLoader(ae_dataset, batch_size=batch_size, shuffle=True, num_workers=6)
if use_vae:
    model = models.ae.MultiVAE([200] + [n_items], dropout=0.5)
else:
    model = models.ae.MultiDAE([200] + [n_items], dropout=0.5)
model.cuda()
optimizer = torch.optim.Adam(model.parameters(), lr=5 * 1e-4)
sc = neuralsort.neuralobjs.SC()
lm = -1 
tr_tt = {
    5: [],
    10: []
}
val_tt = {
    5: [],
    10: [],
}
lolis = []
update_count = 0
for epoch in (range(1, 1000 + 1)):
    model = model.train()
    model.training = True
    tr_losses = []
    loss2s =[] 
    # train for one epoch
    for uid, rowl in (loader):
        row = rowl.float().cuda()
        uid = uid.cuda() 
        loss = None 
        if use_vae:
            scores, mu, logvar = model.forward(row)
            if total_anneal_steps > 0:
                anneal_cap = min(anneal_cap, 1. * update_count / total_anneal_steps)
            else:
                anneal = anneal_cap
            loss  = models.ae.loss_function(scores, row, mu, logvar)
            update_count += 1

        else:
            scores = model.forward(row)
            loss  = models.loss.MultinomialLoss(row, scores)

        loss2 = neuMapLoss(sc, scores, row, topk=300, k=5, tau=15.0, use_top=True)
        loss2s.append(loss2.unsqueeze(-1))
        (loss.mean() + 10.0 * loss2.mean()).backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 5)
        tr_losses.append(loss.detach().unsqueeze(-1)) 
        optimizer.step()
    
    if (epoch % 10 == 0):
        tr_loss = torch.cat(tr_losses).mean()
        lo2 = torch.cat(loss2s).mean()
        lolis.append(lo2)
        _in = torch.from_numpy(vin_dense).float().cuda()
        vad_scores, mu, logvar = model.forward(_in)
        vad_loss = models.ae.loss_function(vad_scores, _in, mu, logvar)
        vad_loss.mean().detach().cpu().numpy()
        model.eval()
        model.training=False                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
        wrapper1 = models.ae.implicitWrapper(model, train_data, naive_sparse2tensor, vae=True)
        wrapper2 = models.ae.implicitWrapper(model, vin, naive_sparse2tensor, vae=True)

        
        ret = (tr_loss.detach().cpu().numpy(), vad_loss.mean().detach().cpu().numpy())
        
        for topk in [5, 10]:
            tr_tt[topk].append(ranking_metrics_at_k(wrapper1, empty, train_data, K=topk, num_threads=4)['map'])
            val_tt[topk].append((ranking_metrics_at_k(wrapper2, vin, vo, K=topk, num_threads=4)['map']))
        print(["%0.4f" % x for x in ret], tr_tt[5][-1], tr_tt[10][-1],val_tt[5][-1], val_tt[10][-1])
        qed.append(ret)
add = qed

['294.7231', '225.8089'] 0.21826278174821165 0.17152883630953158 0.05616430555555556 0.05015200877110111
['274.4365', '219.9437'] 0.2750879604178133 0.21030542590868131 0.06868902777777773 0.06192627480158732
['280.2097', '216.5288'] 0.35857614073666827 0.2742169076872701 0.08582458333333337 0.07594075207860913
['275.0313', '214.3504'] 0.400465457210921 0.3105787457333225 0.09942861111111095 0.08769221812799184
['267.6081', '212.9479'] 0.43259849734286077 0.33781472371745475 0.10510222222222197 0.09244149911816571
['263.7416', '212.0777'] 0.4634359538207799 0.3622940053920485 0.1130180555555553 0.09898759511211869
['266.4737', '211.8793'] 0.4883085944658228 0.3832880855266988 0.11566236111111074 0.10196724600025156
['272.7971', '211.2510'] 0.509337548103352 0.401759022361108 0.11879930555555519 0.10581691649344904
['262.5125', '211.0949'] 0.5284835990470935 0.4176413090331327 0.12163013888888845 0.10819690641534364
['274.7474', '210.6121'] 0.5448414879970654 0.4326874071712478 0.122983

['259.1045', '214.6977'] 0.9268123511086737 0.8329643437506576 0.13897249999999972 0.12617133739606934
['265.1940', '214.8335'] 0.9272796408283005 0.8339701823529737 0.13918958333333298 0.12575000543272832
['263.5654', '214.5125'] 0.9297067986072995 0.8383749975414234 0.13796916666666656 0.1252059786785081
['258.7459', '214.9248'] 0.9311599780099016 0.8402338847446248 0.139772083333333 0.12628875015747018
['265.3243', '214.5748'] 0.931131574124983 0.8416007946965607 0.13900611111111094 0.12567849434681252
['257.1082', '214.8861'] 0.934390690855788 0.8463302887354356 0.13806486111111108 0.12572311799256713
['264.7551', '214.9235'] 0.9347544438336146 0.846072154675306 0.13944319444444422 0.1265741059618291
['264.0295', '215.1135'] 0.9377350192413472 0.8498813985615058 0.1396763888888886 0.12661996779730392
['264.2753', '214.9118'] 0.9366208539490622 0.84978738020823 0.1380765277777774 0.12572762117346908
['258.3012', '214.8421'] 0.9376378962800136 0.8499655549741576 0.1372198611111109 0.

In [16]:
lolis

[tensor(-0.4817, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-0.7677, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.0045, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.1744, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.2924, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.3773, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.4989, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.5715, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.5790, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.6430, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.7150, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.7087, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.7785, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.7870, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.8957, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.8911, device='cuda:0', grad_fn=<MeanBackward0>),
 tensor(-1.9152, device='cuda:0', grad_f